### ISSUE TITLE
Implement Poseidon hash function for EdDSA

### ISSUE THREAD

**Issue by staaason** [ZpokenWeb3/mpc-tss-lib#2]
- [x]  test hash: [go-iden3-crypto](https://github.com/iden3/go-iden3-crypto)
- [x]  add hash as dependency to the existing project, use the go-iden3-crypto package
- [x] hash utils common folder
- [x] integration into EdDSA folder for:
   - [x] keygen
    - [x] resharing
    - [x] signing
- [ ] append end-to-end cycle with keygen -> resharing -> signing

**Comment by xma0s** [comment]
- [ ]  test hash: [go-iden3-crypto](https://github.com/iden3/go-iden3-crypto)

- [ ]  add hash as dependency to the existing project, use the go-iden3-crypto package

- [ ] hash utils common folder

- [ ] integration into EdDSA folder for:

- [ ] keygen

- [ ] resharing

- [ ] signing

**Comment by xma0s** [comment]
- [ ] append end-to-end cycle with keygen -> resharing -> signing
